#!/usr/bin/bash

set -u
set -e

source /usr/libexec/zram-utils/zram.conf

if [ -f /etc/sysconfig/zram ]; then
    source /etc/sysconfig/zram || true
fi

err() {
    printf "%s\n" "$*" 1>&2
    exit 1
}

process_swap_size() {
    local suffix ignore memtotal

    if [[ "$SWAP_SIZE" != +([0-9])?([%GKM]) ]]; then
	err "zram SWAP_SIZE does not match [0-9]+[%GKM]? format - $SWAP_SIZE"
    fi

    suffix="${SWAP_SIZE##*[0-9]}"
    if [ -n "$suffix" ]; then
	SWAP_SIZE=${SWAP_SIZE%$suffix}
	case "$suffix" in
	    G ) SWAP_SIZE=$(($SWAP_SIZE * 1024 * 1024 * 1024));;
	    M ) SWAP_SIZE=$(($SWAP_SIZE * 1024 * 1024));;
	    K ) SWAP_SIZE=$(($SWAP_SIZE * 1024));;
	    % )
		read ignore memtotal < <(grep -o '\<MemTotal:\s\+[0-9]\+' /proc/meminfo)
		SWAP_SIZE=$(($memtotal * $SWAP_SIZE / 100 * 1024))
		;;
	esac
    fi
}

[ -z "${EXTRA_DEVICES##[0-9]}" ] || \
    err "EXTRA_DEVICES value '$EXTRA_DEVICES' is not zero or positive integer"
    
process_swap_size

num_cpus=$(grep -c processor /proc/cpuinfo)
if [ 0 = "$num_cpus" ]; then
    num_cpus=1
fi

/usr/sbin/rmmod zram > /dev/null 2>&1 || true
/usr/sbin/modprobe -q zram num_devices=$((1 + $EXTRA_DEVICES)) > /dev/null 2>&1

echo $num_cpus > /sys/block/zram0/max_comp_streams

if [ $SWAP_SIZE -gt 0 ]; then
    echo "${SWAP_SIZE}" > /sys/block/zram0/disksize
    
    /usr/sbin/mkswap /dev/zram0
    /usr/sbin/swapon -p 100 /dev/zram0
fi
